# Introduction to Numpy

In [1]:
import numpy as np

## 1. Data Types and Data Structure

### Numpy Array

In [3]:
# 1 dimensional array
a1 = np.array([ 1, 2, 3])
a1

array([1, 2, 3])

In [4]:
# 2 dimensional array
a2 = np.array([[12, 32.3, 50], [5.5, 73, 10]])
a2

array([[12. , 32.3, 50. ],
       [ 5.5, 73. , 10. ]])

In [5]:
# 3 dimensional array
a3 = np.array([
    [[1, 2, 3], 
     [4, 5, 6], 
     [7, 8, 9]],
    [[10, 11, 12], 
     [13, 14, 15], 
     [16, 17, 18]]
])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### Properties

In [6]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [7]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [8]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [9]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [10]:
a1.size, a2.size, a3.size

(3, 6, 18)

### Creating Pandas Data Frame from Numpy Array

In [12]:
import pandas as pd

In [13]:
df = pd.DataFrame(a2)
df

0     1     2
0  12.0  32.3  50.0
1   5.5  73.0  10.0

## 2. Creating Arrays

In [16]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [17]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
range = np.arange(0, 10, 2)
range

array([0, 2, 4, 6, 8])

In [22]:
random_array_1 = np.random.randint(0, 100, size=(3, 5))
random_array_1

array([[58,  8, 48, 35, 61],
       [46, 50, 54,  6, 82],
       [50, 25, 51, 73, 28]])

In [23]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.1128827 , 0.94253306, 0.79148425],
       [0.9078649 , 0.06346784, 0.5610032 ],
       [0.47006515, 0.16560741, 0.98402657],
       [0.2421455 , 0.75459701, 0.50370789],
       [0.31297373, 0.1241396 , 0.07736269]])

In [24]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.04123913, 0.21518934, 0.46702595],
       [0.85121008, 0.39426901, 0.75856793],
       [0.18573891, 0.01144942, 0.67977632],
       [0.2546063 , 0.07614259, 0.48414352],
       [0.75076551, 0.00258801, 0.96123251]])

### Using Random Seed

In [26]:
np.random.seed(1)
random_array_4 = np.random.randint(0, 100, size=(5,3))
random_array_4

array([[37, 12, 72],
       [ 9, 75,  5],
       [79, 64, 16],
       [ 1, 76, 71],
       [ 6, 25, 50]])

In [29]:
np.random.seed(200)
random_array_5 = np.random.random((4,7))
random_array_5

array([[0.94763226, 0.22654742, 0.59442014, 0.42830868, 0.76414069,
        0.00286059, 0.35742368],
       [0.90969489, 0.45608099, 0.98180271, 0.86735699, 0.98602751,
        0.92326671, 0.30369331],
       [0.84610349, 0.12122197, 0.78557629, 0.25050505, 0.09602971,
        0.94349104, 0.82605015],
       [0.51832513, 0.87350042, 0.57837569, 0.4500845 , 0.68015698,
        0.41942562, 0.64039346]])

## 3. Viewing Arrays

In [31]:
np.unique(a1), np.unique(a2)

(array([1, 2, 3]), array([ 5.5, 10. , 12. , 32.3, 50. , 73. ]))

In [32]:
a1

array([1, 2, 3])

In [35]:
a1[1]

2

In [36]:
a2

array([[12. , 32.3, 50. ],
       [ 5.5, 73. , 10. ]])

In [38]:
a2[0, 1]

32.3

In [39]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [54]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [55]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[3, 1, 8, 0, 4],
         [6, 3, 4, 4, 6],
         [2, 0, 4, 0, 9],
         [4, 2, 7, 1, 8]],

        [[6, 7, 1, 9, 1],
         [7, 5, 8, 1, 1],
         [1, 7, 0, 2, 6],
         [5, 1, 1, 1, 8]],

        [[3, 0, 7, 8, 4],
         [3, 6, 0, 7, 9],
         [1, 5, 4, 1, 4],
         [5, 7, 2, 0, 9]]],


       [[[7, 0, 5, 4, 6],
         [6, 9, 6, 7, 0],
         [2, 2, 0, 8, 3],
         [4, 8, 1, 1, 8]],

        [[0, 2, 3, 4, 7],
         [8, 1, 4, 8, 4],
         [6, 3, 3, 0, 4],
         [2, 5, 9, 5, 5]],

        [[8, 8, 4, 1, 2],
         [1, 8, 5, 8, 5],
         [4, 6, 4, 6, 0],
         [7, 8, 4, 4, 0]]]])

In [63]:
a4[:,:2,:4,:2]

array([[[[3, 1],
         [6, 3],
         [2, 0],
         [4, 2]],

        [[6, 7],
         [7, 5],
         [1, 7],
         [5, 1]]],


       [[[7, 0],
         [6, 9],
         [2, 2],
         [4, 8]],

        [[0, 2],
         [8, 1],
         [6, 3],
         [2, 5]]]])

## 4. Manipulating and Comparing Arrays

### Arithmetic

#### Addition

In [65]:
a1

array([1, 2, 3])

In [66]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [67]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

#### Subtraction

In [68]:
a1

array([1, 2, 3])

In [69]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [70]:
a1 - ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [72]:
a2

array([[12. , 32.3, 50. ],
       [ 5.5, 73. , 10. ]])

In [73]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [71]:
a2 - ones

array([[11. , 31.3, 49. ],
       [ 4.5, 72. ,  9. ]])

#### Multiplication

In [74]:
a1

array([1, 2, 3])

In [75]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [76]:
a1 * ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [77]:
a2

array([[12. , 32.3, 50. ],
       [ 5.5, 73. , 10. ]])

In [78]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [79]:
a2 * ones

array([[12. , 32.3, 50. ],
       [ 5.5, 73. , 10. ]])

In [80]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [81]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [83]:
a3.shape, ones.shape

((2, 3, 3), (2, 3))

In [93]:
ones[np.newaxis]

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [92]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [98]:
ones[np.newaxis].shape

(1, 2, 3)

In [95]:
a3.shape

(2, 3, 3)

We used np.newaxis to add another dimension to our array to make the shape compatible for broadcast

In [102]:
ones[:, :, np.newaxis]

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [100]:
ones[:, :, np.newaxis].shape

(2, 3, 1)

In [101]:
a3 * ones[:, :, np.newaxis]

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]]])

#### Division

In [103]:
a1

array([1, 2, 3])

In [104]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [105]:
a1 / ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [106]:
a2

array([[12. , 32.3, 50. ],
       [ 5.5, 73. , 10. ]])

In [107]:
a2 / ones

array([[12. , 32.3, 50. ],
       [ 5.5, 73. , 10. ]])

In [108]:
a3 

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [110]:
a3 / ones[:, :, np.newaxis]

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]]])

#### Power

In [111]:
a1 

array([1, 2, 3])

In [113]:
a1 ** 2

array([1, 4, 9])

#### Floor Division

In [116]:
a2

array([[12. , 32.3, 50. ],
       [ 5.5, 73. , 10. ]])

In [117]:
a1

array([1, 2, 3])

In [118]:
a2 // a1

array([[12., 16., 16.],
       [ 5., 36.,  3.]])

#### Modulus

In [119]:
a1

array([1, 2, 3])

In [120]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [121]:
a3 

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [122]:
a3 % 2

array([[[1, 0, 1],
        [0, 1, 0],
        [1, 0, 1]],

       [[0, 1, 0],
        [1, 0, 1],
        [0, 1, 0]]], dtype=int32)