# Introduction to Numpy

In [1]:
import numpy as np

## Data Types and Data Structure

### Numpy Array

In [3]:
# 1 dimensional array
a1 = np.array([ 1, 2, 3])
a1

array([1, 2, 3])

In [4]:
# 2 dimensional array
a2 = np.array([[12, 32.3, 50], [5.5, 73, 10]])
a2

array([[12. , 32.3, 50. ],
       [ 5.5, 73. , 10. ]])

In [5]:
# 3 dimensional array
a3 = np.array([
    [[1, 2, 3], 
     [4, 5, 6], 
     [7, 8, 9]],
    [[10, 11, 12], 
     [13, 14, 15], 
     [16, 17, 18]]
])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### Properties

In [6]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [7]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [8]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [9]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [10]:
a1.size, a2.size, a3.size

(3, 6, 18)

### Creating Pandas Data Frame from Numpy Array

In [12]:
import pandas as pd

In [13]:
df = pd.DataFrame(a2)
df

0     1     2
0  12.0  32.3  50.0
1   5.5  73.0  10.0

## Creating Arrays

In [16]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [17]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
range = np.arange(0, 10, 2)
range

array([0, 2, 4, 6, 8])

In [22]:
random_array_1 = np.random.randint(0, 100, size=(3, 5))
random_array_1

array([[58,  8, 48, 35, 61],
       [46, 50, 54,  6, 82],
       [50, 25, 51, 73, 28]])

In [23]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.1128827 , 0.94253306, 0.79148425],
       [0.9078649 , 0.06346784, 0.5610032 ],
       [0.47006515, 0.16560741, 0.98402657],
       [0.2421455 , 0.75459701, 0.50370789],
       [0.31297373, 0.1241396 , 0.07736269]])

In [24]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.04123913, 0.21518934, 0.46702595],
       [0.85121008, 0.39426901, 0.75856793],
       [0.18573891, 0.01144942, 0.67977632],
       [0.2546063 , 0.07614259, 0.48414352],
       [0.75076551, 0.00258801, 0.96123251]])